/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_josuevidal;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author josue
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_home = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jd_pelicula = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nombrep = new javax.swing.JTextField();
        tf_director = new javax.swing.JTextField();
        tf_duracionp = new javax.swing.JTextField();
        tf_idioma = new javax.swing.JTextField();
        tf_compania = new javax.swing.JTextField();
        tf_actorp = new javax.swing.JTextField();
        tf_doblaje = new javax.swing.JTextField();
        tf_subtitulos = new javax.swing.JTextField();
        cb_categoriap = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jd_serie = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        tf_duracions = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_idiomas = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_productora = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_actors = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_doblajes = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_subtituloss = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cb_categorias = new javax.swing.JComboBox<>();
        tf_nombres = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        tf_temporadas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Nesflis");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("nesflis");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_arbol);

        jButton1.setText("Agregar Pelicula");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Agregar Serie");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton5.setText("Salir y guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton7.setText("Cargar al arbol");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_homeLayout = new javax.swing.GroupLayout(jd_home.getContentPane());
        jd_home.getContentPane().setLayout(jd_homeLayout);
        jd_homeLayout.setHorizontalGroup(
            jd_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_homeLayout.createSequentialGroup()
                        .addGroup(jd_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_homeLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_homeLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButton1)
                                .addGap(72, 72, 72)
                                .addComponent(jButton2)))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_homeLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(81, 81, 81)
                        .addComponent(jButton7)
                        .addGap(113, 113, 113))))
            .addGroup(jd_homeLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_homeLayout.setVerticalGroup(
            jd_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jd_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addGap(36, 36, 36))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Agregar pelicula");

        jLabel6.setText("Nombre");

        jLabel7.setText("Duracion");

        jLabel8.setText("Categoria");

        jLabel9.setText("Actor Principal");

        jLabel10.setText("Director");

        jLabel11.setText("Compania");

        jLabel12.setText("Idioma");

        jLabel13.setText("Doblaje");

        jLabel14.setText("Subtitulos");

        cb_categoriap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "suspenso", "terror", "accion", "romance", "ciencia ficcion", "animacion", "fantasia" }));

        jButton4.setText("Agregar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_peliculaLayout = new javax.swing.GroupLayout(jd_pelicula.getContentPane());
        jd_pelicula.getContentPane().setLayout(jd_peliculaLayout);
        jd_peliculaLayout.setHorizontalGroup(
            jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_peliculaLayout.createSequentialGroup()
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_peliculaLayout.createSequentialGroup()
                        .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_peliculaLayout.createSequentialGroup()
                                    .addGap(117, 117, 117)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jd_peliculaLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_duracionp, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_nombrep)
                            .addComponent(tf_actorp, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_director, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_compania, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_idioma, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_doblaje, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_subtitulos)
                            .addComponent(cb_categoriap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_peliculaLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel5))
                    .addGroup(jd_peliculaLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButton4)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jd_peliculaLayout.setVerticalGroup(
            jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_peliculaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_duracionp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_categoriap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_actorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_compania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_doblaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(47, 47, 47)
                .addGroup(jd_peliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_subtitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
        );

        jLabel25.setText("Nombre");

        jLabel26.setText("Duracion");

        jLabel27.setText("Categoria");

        jLabel28.setText("Actor Principal");

        jLabel29.setText("Temporadas");

        jLabel30.setText("Productora");

        jLabel31.setText("Idioma");

        jLabel32.setText("Doblaje");

        jLabel33.setText("Subtitulos");

        cb_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "suspenso", "terror", "accion", "romance", "ciencia ficcion", "animacion", "fantasia" }));

        jButton6.setText("Agregar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel34.setText("Agregar Serie");

        tf_temporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_temporadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_serieLayout = new javax.swing.GroupLayout(jd_serie.getContentPane());
        jd_serie.getContentPane().setLayout(jd_serieLayout);
        jd_serieLayout.setHorizontalGroup(
            jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_serieLayout.createSequentialGroup()
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_serieLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_serieLayout.createSequentialGroup()
                                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jd_serieLayout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel26))
                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jd_serieLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel29))
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(44, 44, 44)
                                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_duracions)
                                    .addComponent(tf_nombres)
                                    .addComponent(tf_actors)
                                    .addComponent(tf_temporadas)
                                    .addComponent(tf_productora)
                                    .addComponent(tf_idiomas)
                                    .addComponent(tf_doblajes)
                                    .addComponent(tf_subtituloss)
                                    .addComponent(cb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_serieLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel34))))
                    .addGroup(jd_serieLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton6)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jd_serieLayout.setVerticalGroup(
            jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_serieLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel34)
                .addGap(46, 46, 46)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_duracions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(31, 31, 31)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_actors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(40, 40, 40)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_temporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(36, 36, 36)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_productora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(32, 32, 32)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_idiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(40, 40, 40)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_doblajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(47, 47, 47)
                .addGroup(jd_serieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_subtituloss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Log in");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contra");

        Ingresar.setText("Ingresar");
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77)
                                .addComponent(tf_usuario)))))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(Ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(Ingresar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_pelicula.setModal(true);
        jd_pelicula.pack();
        jd_pelicula.setLocationRelativeTo(this);
        jd_pelicula.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_serie.setModal(true);
        jd_serie.pack();
        jd_serie.setLocationRelativeTo(this);
        jd_serie.setVisible(true);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try {
            AdministrarPelicula ap = new AdministrarPelicula("./Peliculas.txt");
            ap.cargarArchivo();

            ap.getListaPeliculas().add(new Pelicula(tf_nombrep.getText(), Integer.parseInt(tf_duracionp.getText()), cb_categoriap.getSelectedItem().toString(), tf_actorp.getText(), tf_director.getText(), tf_compania.getText(), tf_idioma.getText(), tf_doblaje.getText(), tf_subtitulos.getText()));
            ap.esccribirArchivo();
            System.out.println(ap.getListaPeliculas());
            
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            DefaultMutableTreeNode k = new DefaultMutableTreeNode("PELICULAS");
            //obtener la persona a guardar
            int centinela = -1;
            for (Pelicula i : ap.getListaPeliculas()) {

                for (int j = 0; j < raiz.getChildCount(); j++) {
                    if (raiz.getChildAt(j).toString().equals(cb_categoriap.getSelectedItem().toString())) {
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Pelicula(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getDirector(), i.getCompania(), i.getIdioma(), i.getDoblaje(), i.getSubtitulos()));
                        ((DefaultMutableTreeNode) k.getChildAt(j)).add(p);
                        centinela = 1;
                    }
                }
                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(cb_categoriap.getSelectedItem().toString());
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Pelicula(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getDirector(), i.getCompania(), i.getIdioma(), i.getDoblaje(), i.getSubtitulos()));
                    DefaultMutableTreeNode h = new DefaultMutableTreeNode("PELICULAS");
                    n.add(p);
                    k.add(n);
                    raiz.add(k);
                }
                modeloARBOL.reload();
            }

        } catch (Exception e) {
        }
        jd_pelicula.setVisible(false);


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try {
            AdministrarSerie as = new AdministrarSerie("./Series.txt");
            as.cargarArchivo();

            as.getListaSeries().add(new Serie(tf_nombres.getText(), Integer.parseInt(tf_duracions.getText()), cb_categorias.getSelectedItem().toString(), tf_actors.getText(), Integer.parseInt(tf_temporadas.getText()), tf_productora.getText(), tf_idiomas.getText(), tf_doblajes.getText(), tf_subtituloss.getText()));
            as.esccribirArchivo();
            System.out.println(as.getListaSeries());

            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            DefaultMutableTreeNode k = new DefaultMutableTreeNode("SERIES");
            //obtener la persona a guardar
            int centinela = -1;
            for (Serie i : as.getListaSeries()) {

                for (int j = 0; j < raiz.getChildCount(); j++) {
                    if (raiz.getChildAt(j).toString().equals(cb_categorias.getSelectedItem().toString())) {
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Serie(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getTemporadas(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubtitulos()));
                        ((DefaultMutableTreeNode) k.getChildAt(j)).add(p);
                        centinela = 1;
                    }
                }
                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(cb_categorias.getSelectedItem().toString());
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Serie(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getTemporadas(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubtitulos()));
                    DefaultMutableTreeNode h = new DefaultMutableTreeNode("SERIES");
                    n.add(p);
                    k.add(n);
                    raiz.add(k);
                }
                modeloARBOL.reload();
            }
            jd_serie.setVisible(false);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton6MouseClicked

    private void tf_temporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_temporadasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_temporadasActionPerformed

    private void IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseClicked
        // TODO add your handling code here:
        AdmiistrarUsuario au = new AdmiistrarUsuario("./Usuarios.txt");
        // for (int i = 0; i < au.getListaUsuarios().size(); i++) {
        //  if (au.getListaUsuarios().get(i).getUsuario().equals(tf_usuario.getText()) && au.getListaUsuarios().get(i).getContra().equals(tf_contra.getText())) {
        jd_home.setModal(true);
        jd_home.pack();
        jd_home.setLocationRelativeTo(this);
        jd_home.setVisible(true);
        //  }
        //}
    }//GEN-LAST:event_IngresarMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        AdministrarSerie as = new AdministrarSerie("./Series.txt");
        DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        DefaultMutableTreeNode k = new DefaultMutableTreeNode("SERIES");
        //obtener la persona a guardar
        int centinela = -1;
        for (Serie i : as.getListaSeries()) {

            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(cb_categorias.getSelectedItem().toString())) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Serie(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getTemporadas(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubtitulos()));
                    ((DefaultMutableTreeNode) k.getChildAt(j)).add(p);
                    centinela = 1;
                }
            }
            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(cb_categorias.getSelectedItem().toString());
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Serie(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getTemporadas(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubtitulos()));
                DefaultMutableTreeNode h = new DefaultMutableTreeNode("SERIES");
                n.add(p);
                k.add(n);
                raiz.add(k);
            }
            modeloARBOL.reload();
        }
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JComboBox<String> cb_categoriap;
    private javax.swing.JComboBox<String> cb_categorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_home;
    private javax.swing.JDialog jd_pelicula;
    private javax.swing.JDialog jd_serie;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTextField tf_actorp;
    private javax.swing.JTextField tf_actors;
    private javax.swing.JTextField tf_compania;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_director;
    private javax.swing.JTextField tf_doblaje;
    private javax.swing.JTextField tf_doblajes;
    private javax.swing.JTextField tf_duracionp;
    private javax.swing.JTextField tf_duracions;
    private javax.swing.JTextField tf_idioma;
    private javax.swing.JTextField tf_idiomas;
    private javax.swing.JTextField tf_nombrep;
    private javax.swing.JTextField tf_nombres;
    private javax.swing.JTextField tf_productora;
    private javax.swing.JTextField tf_subtitulos;
    private javax.swing.JTextField tf_subtituloss;
    private javax.swing.JTextField tf_temporadas;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
